Repository honeycombio/beeline-ruby, pull requests merged in 2022-04, with the labels that each got.

#199 Prepare v2.10.0 release
  CHANGELOG.md
  lib/honeycomb/beeline/version.rb
Labels: type: maintenance, version: bump minor

#201 Console: Load the file that exists
  bin/console
Labels: type: maintenance, version: no bump

#202 Update Ruby and puma in the example
  examples/rails52/Dockerfile
  examples/rails52/Gemfile
Labels: type: maintenance, version: no bump, merge at will
