Repository honeycombio/beeline-ruby, pull requests merged in 2023-10, with the labels that each got.

#232 fix: clean invalid UTF8 from trace field values when generating propagation header
  .rubocop.yml
  lib/honeycomb/propagation/default_modern.rb
  lib/honeycomb/propagation/honeycomb.rb
  lib/honeycomb/propagation/honeycomb_modern.rb
  spec/honeycomb/propagation/honeycomb_modern_spec.rb
  spec/honeycomb/propagation/honeycomb_spec.rb
Labels: type: bug, version: bump patch, status: oncall

#233 maint: add local dev notes and fix example
  .gitignore
  DEVELOPING.md
  examples/rails52/Gemfile
  examples/rails52/docker-compose.yml
Labels: type: maintenance, type: documentation, version: no-bump

#234 rel: prep v3.0.1
  CHANGELOG.md
  RELEASING.md
  lib/honeycomb/beeline/version.rb
Labels: no-changelog
