Repository honeycombio/beeline-ruby, pull requests merged in 2023-01, with the labels that each got.

#218 fix: set min rubocop to avoid false positive lint error
  honeycomb-beeline.gemspec
Labels: type: bug, version: no bump, status: oncall, no-changelog

#219 ci: use context for publishing ruby gem
  .circleci/config.yml
  .circleci/setup-rubygems.sh
Labels: type: maintenance, version: no bump, no-changelog

#220 maint: update author to honeycomb
  .github/CODEOWNERS
  honeycomb-beeline.gemspec
Labels: type: maintenance, version: no bump
