Repository honeycombio/beeline-ruby, pull requests merged in 2024-03, with the labels that each got.

#239 maint: add labels to release.yml for auto-generated grouping
  .github/release.yml
Labels: type: maintenance, version: no bump, no-changelog

#238 feat: support classic ingest keys
  honeycomb-beeline.gemspec
  lib/honeycomb/client.rb
  lib/honeycomb/configuration.rb
  spec/honeycomb/configuration_spec.rb
Labels: type: enhancement, version: bump minor

#240 rel: 3.1.0
  CHANGELOG.md
  lib/honeycomb/beeline/version.rb
Labels: no-changelog
